public enum RomanNumeral {
    I(1), II(2), III(3), IV(4), V(5), VI(6) , VII(7), VIII(8), IX(9), X(10),
    XI, XII, XIII, XIV, XV, XVI, XVII, XVIII, XIX, XX,
    XXI, XXII, XXIII, XXIV, XXV, XXVI, XXVII, XXVIII, XXIX, XXX,
    XXXI, XXXII, XXXIII, XXXIV, XXXV, XXXVI, XXXVII, XXXVIII, XXXIX, XL,
    XLI, XLII, XLIII, XLIV, XLV, XLVI, XLVII, XLVIII, XLIX, L,
    LI, LII, LIII, LIV, LV, LVI, LVII, LVIII, LIX, LX,
    LXI, LXII, LXIII, LXIV, LXV, LXVI, LXVII, LXVIII, LXIX, LXX,
    LXXI, LXXII, LXXIII, LXXIV, LXXV, LXXVI, LXXVII, LXXVIII, LXXIX, LXXX,
    LXXXI, LXXXII, LXXXIII, LXXXIV, LXXXV, LXXXVI, LXXXVII, LXXXVIII, LXXXIX, XC,
    XCI, XCII, XCIII, XCIV, XCV, XCVI, XCVII, XCVIII, XCIX, C;
    int index;
    RomanNumeral(){

    }

    RomanNumeral(int index) {
        this.index = index;
    }
}
